name: go_foundation
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.9.0
  retrofit: ^4.4.0
  dio: ^5.4.3+1
  retrofit_generator: ^9.6.0
  realm: ^20.2.0
  uuid: ^4.4.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.13


flutter: 
  assets:
    - assets/icons/
    - .env
  uses-material-design: true
